version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Deploying to Lambda...
      - aws lambda update-function-code --function-name flaskLambdaApp --zip-file fileb://flask-app.zip

artifacts:
  files: []
