version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt -t build/

  build:
    commands:
      - echo Packaging application...
      - mkdir -p temp
      - rsync -av --exclude=build --exclude=temp ./ temp/
      - cp -r temp/* build/
      - cd build
      - zip -r ../flask-app.zip .
      - cd ..

artifacts:
  files:
    - flask-app.zip
  discard-paths: yes
