AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: flask-lambda
      Runtime: python3.9
      Handler: app.handler
      CodeUri:
        Bucket: chirags3flasktest
        Key: flask-app.zip
      MemorySize: 128
      Timeout: 10
      Events:
        FlaskApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
